### ISSUE TITLE
java.lang.Throwable: Assert: must be called on EDT

### ISSUE THREAD

**Issue by ken209** [niftythoughts/ansi-highlighter-premium#10]
idea version:2023.2.3
ansi version:23.2.0

java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.ide.ui.laf.LafManagerImpl.initializeComponent(LafManagerImpl.kt:295)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:133)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:577)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:94)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.intellij.ide.ui.LafManager.getInstance(LafManager.java:18)
	at

**Comment by niftythoughts** [comment]
The shared stack trace doesn't necessarily link to ANSI Highlighter. Can you share the steps to reproduce the bug + the full stack trace?
